services:
  activemq-artemis:
    image: apache/activemq-artemis:latest-alpine
    hostname: activemq-artemis
    container_name: activemq-artemis
    volumes:
      - ./etc-override:/var/lib/artemis-instance/etc-override
    ports:
      - 61616:61616
      - 61613:61613
      - 8161:8161
